#!/usr/bin/env bash

installtodevbin () {
  APP=$1
  if [ -f $(pwd)/$APP ]; then
    if [ -f $HOME/bin/$APP ]; then
      rm -v $HOME/bin/$APP
    fi
    ln -sv $(pwd)/$APP $HOME/bin/$APP
  else
    echo "App Not Found '$APP' ..." 
  fi
}

installtodevbin dst-install
installtodevbin dst-update
installtodevbin jwd-create-web-app

installtodevbin dst-edit-tool
installtodevbin dst-create-gitignore
installtodevbin dst-list-gitignoreio-types
installtodevbin foa-create-react
installtodevbin fba-create-dotnet-app
installtodevbin dst-install-rvm
installtodevbin fba-create-dotnet-api
installtodevbin dst-copy-ssh-key
installtodevbin dst-int-set-docker-host
installtodevbin dst-ext-set-docker-host
installtodevbin dst-install-aws-cli
installtodevbin aer-get-repositories
installtodevbin aer-create-repository
installtodevbin aer-delete-repository
installtodevbin aer-docker-login
installtodevbin aer-docker-tag
installtodevbin aer-docker-push
installtodevbin aer-docker-build
installtodevbin aws-ecr-login
installtodevbin aws-list-images-in-repo
installtodevbin aws-list-repos
installtodevbin aws-list-repourls
installtodevbin aws-pull-image
installtodevbin aws-push-image
