#!/usr/bin/env bash
APP=$1
DSTP=$HOME/bin/dst-install
DSTD=`dirname $(readlink $HOME/bin/dst-install)`

if [ -f $HOME/bin/dst-install ]; then
  cd $DSTD
  if [ ! -f $APP ]; then
    echo "Creating APP $APP .... "
    touch $APP
    echo "#!/usr/bin/env bash" > $APP
  fi
  chmod -v a+x $APP
  vim $APP
  LINE="installtodevbin $1"
  FILE="$HOME/bin/dst-install"
  grep -qF -- "$LINE" "$FILE" || echo "$LINE" >> "$FILE"
fi
