#!/usr/bin/env bash

installtodevbin () {
  APP=$1
  if [ -f $(pwd)/$APP ]; then
    if [ -f $HOME/bin/$APP ]; then
      rm -v $HOME/bin/$APP
    fi
    ln -sv $(pwd)/$APP $HOME/bin/$APP
  else
    echo "App Not Found '$APP' ..." 
  fi
}

installtodevbin dst-install
installtodevbin dst-update
installtodevbin jwd-create-web-app

installtodevbin dst-edit-tool
installtodevbin dst-create-gitignore
installtodevbin dst-list-gitignoreio-types
installtodevbin foa-create-react
installtodevbin fba-create-dotnet-app
installtodevbin dst-install-rvm
installtodevbin fba-create-dotnet-api
installtodevbin dst-copy-ssh-key
installtodevbin dst-int-set-docker-host
installtodevbin dst-ext-set-docker-host
installtodevbin dst-install-aws-cli
installtodevbin aer-get-repositories
installtodevbin aer-create-repository
installtodevbin aer-delete-repository
installtodevbin aer-docker-login
installtodevbin aer-docker-tag
installtodevbin aer-docker-push
installtodevbin aer-docker-build
installtodevbin aws-ecr-login
installtodevbin aws-list-images-in-repo
installtodevbin aws-list-repos
installtodevbin aws-list-repourls
installtodevbin aws-pull-image
installtodevbin aws-push-image
installtodevbin idf-create-dockerfile
installtodevbin dst-install-mongodb-brew
installtodevbin dst-start-mongodb-brew
installtodevbin jad-create-app
installtodevbin jde-install-tomcat
installtodevbin jde-install-payara
installtodevbin jde-install-wildfly
installtodevbin jde-setup
installtodevbin jva-dev-workspaces-setup
installtodevbin jde-tomcat-start
installtodevbin jde-tomcat-stop
installtodevbin jde-tomcat-edit-users
installtodevbin jde-tomcat-edit-conf
installtodevbin jde-tomcat-copy-to-lib
installtodevbin jde-download-mysql-jdbc
installtodevbin jde-wildfly-start
installtodevbin jde-wildfly-stop
installtodevbin jde-payara-start
installtodevbin jde-payara-stop
installtodevbin jwd-create-jee-app
installtodevbin njs-run-ts-standard
installtodevbin njs-run-ts-standard-fix
installtodevbin jwd-create-quarkus-app
installtodevbin dnc-create-sln
installtodevbin dnc-create-fsharp-console
